### PR TITLE
Logout Button

### PR DESCRIPTION
**Pull request by alexanderkatz**
Users can logout from admin-blogroll-view. 
Removed menu from header.ejs because it is no longer needed.

### CODE REVIEW

**Comment by alexanderkatz** [comment]
Correct, I created a task for this in Trello, but will go ahead and fix it now.

**Comment by alexanderkatz** [comment]
@ibrand I fixed it, but it only works in dev because I had to specify the url with port 8080. We can make it work in both later if we use config vars.

**Comment by ibrand** [comment]
oh ok  didn't realize. Also it might have conflicts because of the no-more-userlist stuff. If that's the case the merge conflicts will be super easy to fix.

**Comment by ibrand** [comment]
@alexanderkatz Make sure to fix the merge conflicts before merge (merge master into the branch on your terminal) but otherwise go ahead and merge

**Comment by alexanderkatz** [comment]
@ibrand This is ready for review. 
- Cheeya

**Pull request merged**
